#!/bin/bash 

#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p gpu
#SBATCH -A UH-COSC6374-18F-Para
#SBATCH -t 00:30:00
#SBATCH -J job-matmul
#SBATCH -o job-matmul.o%j.stdout
#SBATCH -e job-matmul.%j.error
module load cuda

./matmul

